In [25]:
import numpy as np
import pandas as pd

In [26]:
df1= pd.read_csv("../modeling/_AccommodationDetail__202607062338.csv")
df2=pd.read_csv("../modeling/_TourSpot__202607062337.csv")

In [27]:
print(df1)
print(df2)

     temp_room_id  spot_id  room_code room_title  room_size_pyeong  \
0               1  3102030        NaN       한옥독채                30
1               1  3102108        NaN         독채                13
2               1  3102089        NaN         본채                10
3               2  3102089        NaN        사랑채                13
4               3  3102089        NaN         안채                20
..            ...      ...        ...        ...               ...
325             2  3106623        NaN         알천                 0
326             3  3106623        NaN        포석정                 0
327             4  3106623        NaN         계림                 0
328             5  3106623        NaN        반월성                 0
329             1  3049878        NaN       트윈베드                 0

     room_size_square_meter  room_count  base_count  max_count  \
0                      99.2           1           4         10
1                      43.0           1           2          4
2                      33.1           2           2          3
3                      43.0           2           2          3
4                      66.2           1           2          4
..                      ...         ...         ...        ...
325                     0.0           1           2          3
326                     0.0           1           2          4
327                     0.0           1           2          2
328                     0.0           1           2          3
329                     0.0           0           0          0

     offseason_weekday_min_fee  ...  has_tv  has_pc  has_cable has_internet  \
0                            0  ...       Y     NaN          Y            Y
1                       400000  ...       Y     NaN        NaN            Y
2                       200000  ...       Y     NaN          Y            Y
3                       300000  ...       Y     NaN          Y            Y
4                       350000  ...       Y     NaN          Y            Y
..                         ...  ...     ...     ...        ...          ...
325                     120000  ...       Y     NaN          Y            Y
326                     149000  ...       Y     NaN          Y            Y
327                     130000  ...       Y     NaN          Y            Y
328                     149000  ...       Y     NaN          Y            Y
329                          0  ...       Y       Y        NaN          NaN

    has_refrigerator has_toiletries has_sofa has_cook has_table has_hairdryer
0                  Y              Y        Y        Y         Y             Y
1                  Y              Y        Y        Y         Y             Y
2                  Y              Y      NaN      NaN       NaN             Y
3                  Y              Y      NaN      NaN       NaN             Y
4                  Y              Y      NaN      NaN       NaN             Y
..               ...            ...      ...      ...       ...           ...
325                Y              Y      NaN      NaN         Y             Y
326                Y              Y      NaN      NaN       NaN             Y
327                Y              Y      NaN      NaN       NaN             Y
328                Y              Y      NaN      NaN       NaN             Y
329              NaN            NaN        Y      NaN         Y           NaN

[330 rows x 28 columns]
     spot_id                      name  \
0    2910116                     라라캠핑장
1    2904463                      장터밥상
2     127693                   골굴사(경주)
3    1492402                 경주 대릉원 일원
4    3336522                 통일전 은행나무길
..       ...                       ...
657  2037712                    왕에게 가다
658  2364616  버스로 떠나는 제2의 수학여행 양동마을 코스
659  1945387             경주의 보물을 만나는 길
660  1854171       신라의 화려한 역사와 문화를 만나다
661  1854229        통일신라의 주역이 잠들어 있는 곳

                                                   img  content  \
0    http://tong.visitkorea.or.kr/cms/resource/96/2...      NaN
1    https://tong.visitkorea.or.kr/cms/resource/59/...      NaN
2    https://tong.visitkorea.or.kr/cms/resource/89/...      NaN
3    https://tong.visitkorea.or.kr/cms/resource/71/...      NaN
4    https://tong.visitkorea.or.kr/cms/resource/21/...      NaN
..                                                 ...      ...
657  http://tong.visitkorea.or.kr/cms/resource/66/1...      NaN
658  http://tong.visitkorea.or.kr/cms/resource/34/2...      NaN
659  http://tong.visitkorea.or.kr/cms/resource/43/1...      NaN
660  http://tong.visitkorea.or.kr/cms/resource/48/1...      NaN
661  http://tong.visitkorea.or.kr/cms/resource/61/1...      NaN

                      address  can_parking  can_pet  crowd_level  \
0         경상북도 경주시 서왕길 381-14          NaN      NaN          NaN
1          경상북도 경주시 동해안로 1998          NaN      NaN          NaN
2    경상북도 경주시 문무대왕면 기림로 101-5          NaN      NaN          NaN
3           경상북도 경주시 황남동 31-1          NaN      NaN          NaN
4       경상북도 경주시 칠불암길 6 (남산동)          NaN      NaN          NaN
..                        ...          ...      ...          ...
657                       NaN          NaN      NaN          NaN
658                       NaN          NaN      NaN          NaN
659                       NaN          NaN      NaN          NaN
660                       NaN          NaN      NaN          NaN
661                       NaN          NaN      NaN          NaN

                                              overview  \
0    라라캠핑장은 경북 경주시 양남면 신대리에 자리 잡았다. 경주시청을 기점으로 40㎞가...
1    장터밥상은 경상북도 경주시 감포읍 전촌리에 위치하고 있다. 깔끔한 외관과 고급스러운...
2    골굴사는 경주시의 함월산에 위치한 사찰로 선무도(禪武道)의 총본산으로 한국의 소림사...
3    경주 대릉원은 경주시 노동동과 황남동에 있는 신라 시대의 고분군을 말하며 노동동 고...
4    통일전 은행나무길은 경주시의 대표적인 가을 명소로 손꼽히는 곳이라고 할 수 있다. ...
..                                                 ...
657  국립경주박물관으로 들어서면 커다란 종이 보인다. 경덕왕이 아버지를 기리기 위해 만든...
658  도시 전체가 하나의 거대한 신라박물관인 경주. 유네스코 지정 세계문화유산도 52개나...
659  신라문화의 보물 같은 결정체를 보는 여행이다. 경주 여행에 빼 놓을 수 없는 포석정...
660  경주는 신라시대 역사의 산 교육장이다. 답사 여행은 에밀레종으로 잘 알려진 성덕대왕...
661  경주를 가로지르는 형산강 서쪽은 시내에 비해 사람들의 발길이 뜸하다. 하지만 태종무...

                                              homepage       map_x      map_y  \
0    <a href="https://cafe.naver.com/lalacamp"targe...  129.396364  35.687767
1                                                  NaN  129.490808  35.785516
2                              http://www.golgulsa.com  129.406572  35.802359
3    경주문화관광 http://www.gyeongju.go.kr/tour국가유산청 htt...  129.212800  35.838200
4               경주문화관광 https://www.gyeongju.go.kr/tour  129.242273  35.798198
..                                                 ...         ...        ...
657                                                NaN  129.187842  35.825069
658                                                NaN  129.254651  35.999893
659                                                NaN  129.212863  35.807311
660                                                NaN  129.228603  35.829339
661                                                NaN  129.192394  35.845334

     content_id  content_type_id  tel
0       2910116               28  NaN
1       2904463               39  NaN
2        127693               12  NaN
3       1492402               12  NaN
4       3336522               12  NaN
..          ...              ...  ...
657     2037712               25  NaN
658     2364616               25  NaN
659     1945387               25  NaN
660     1854171               25  NaN
661     1854229               25  NaN

[662 rows x 15 columns]

In [28]:
df2.head()

,spot_id,name,img,content,address,can_parking,can_pet,crowd_level,overview,homepage,map_x,map_y,content_id,content_type_id,tel
0,2910116,라라캠핑장,http://tong.visitkorea.or.kr/cms/resource/96/2...,NaN,경상북도 경주시 서왕길 381-14,NaN,NaN,NaN,라라캠핑장은 경북 경주시 양남면 신대리에 자리 잡았다. 경주시청을 기점으로 40㎞가...,"<a href=""https://cafe.naver.com/lalacamp""targe...",129.396364,35.687767,2910116,28,NaN
1,2904463,장터밥상,https://tong.visitkorea.or.kr/cms/resource/59/...,NaN,경상북도 경주시 동해안로 1998,NaN,NaN,NaN,장터밥상은 경상북도 경주시 감포읍 전촌리에 위치하고 있다. 깔끔한 외관과 고급스러운...,NaN,129.490808,35.785516,2904463,39,NaN
2,127693,골굴사(경주),https://tong.visitkorea.or.kr/cms/resource/89/...,NaN,경상북도 경주시 문무대왕면 기림로 101-5,NaN,NaN,NaN,골굴사는 경주시의 함월산에 위치한 사찰로 선무도(禪武道)의 총본산으로 한국의 소림사...,http://www.golgulsa.com,129.406572,35.802359,127693,12,NaN
3,1492402,경주 대릉원 일원,https://tong.visitkorea.or.kr/cms/resource/71/...,NaN,경상북도 경주시 황남동 31-1,NaN,NaN,NaN,경주 대릉원은 경주시 노동동과 황남동에 있는 신라 시대의 고분군을 말하며 노동동 고...,경주문화관광 http://www.gyeongju.go.kr/tour국가유산청 htt...,129.212800,35.838200,1492402,12,NaN
4,3336522,통일전 은행나무길,https://tong.visitkorea.or.kr/cms/resource/21/...,NaN,경상북도 경주시 칠불암길 6 (남산동),NaN,NaN,NaN,통일전 은행나무길은 경주시의 대표적인 가을 명소로 손꼽히는 곳이라고 할 수 있다. ...,경주문화관광 https://www.gyeongju.go.kr/tour,129.242273,35.798198,3336522,12,NaN

In [29]:
print(df2.columns.tolist())

['spot_id', 'name', 'img', 'content', 'address', 'can_parking', 'can_pet', 'crowd_level', 'overview', 'homepage', 'map_x', 'map_y', 'content_id', 'content_type_id', 'tel']

In [30]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 662 entries, 0 to 661
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   spot_id          662 non-null    int64
 1   name             662 non-null    str
 2   img              507 non-null    str
 3   content          0 non-null      float64
 4   address          646 non-null    str
 5   can_parking      0 non-null      float64
 6   can_pet          0 non-null      float64
 7   crowd_level      0 non-null      float64
 8   overview         661 non-null    str
 9   homepage         387 non-null    str
 10  map_x            662 non-null    float64
 11  map_y            662 non-null    float64
 12  content_id       662 non-null    int64
 13  content_type_id  662 non-null    int64
 14  tel              7 non-null      str
dtypes: float64(6), int64(3), str(6)
memory usage: 668.0 KB

In [31]:
null_ratio = df2.isnull().sum() / len(df2)

# 80% 이상 null인 컬럼 찾기
cols_to_drop = null_ratio[null_ratio >= 0.8].index.tolist()

# 드롭할 컬럼 확인
print(f"드롭할 컬럼: {cols_to_drop}")

# 드롭 실행
df2 = df2.drop(columns=cols_to_drop)

드롭할 컬럼: ['content', 'can_parking', 'can_pet', 'crowd_level', 'tel']

In [32]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 662 entries, 0 to 661
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   spot_id          662 non-null    int64
 1   name             662 non-null    str
 2   img              507 non-null    str
 3   address          646 non-null    str
 4   overview         661 non-null    str
 5   homepage         387 non-null    str
 6   map_x            662 non-null    float64
 7   map_y            662 non-null    float64
 8   content_id       662 non-null    int64
 9   content_type_id  662 non-null    int64
dtypes: float64(2), int64(3), str(5)
memory usage: 641.9 KB

In [33]:
df2.head()

,spot_id,name,img,address,overview,homepage,map_x,map_y,content_id,content_type_id
0,2910116,라라캠핑장,http://tong.visitkorea.or.kr/cms/resource/96/2...,경상북도 경주시 서왕길 381-14,라라캠핑장은 경북 경주시 양남면 신대리에 자리 잡았다. 경주시청을 기점으로 40㎞가...,"<a href=""https://cafe.naver.com/lalacamp""targe...",129.396364,35.687767,2910116,28
1,2904463,장터밥상,https://tong.visitkorea.or.kr/cms/resource/59/...,경상북도 경주시 동해안로 1998,장터밥상은 경상북도 경주시 감포읍 전촌리에 위치하고 있다. 깔끔한 외관과 고급스러운...,NaN,129.490808,35.785516,2904463,39
2,127693,골굴사(경주),https://tong.visitkorea.or.kr/cms/resource/89/...,경상북도 경주시 문무대왕면 기림로 101-5,골굴사는 경주시의 함월산에 위치한 사찰로 선무도(禪武道)의 총본산으로 한국의 소림사...,http://www.golgulsa.com,129.406572,35.802359,127693,12
3,1492402,경주 대릉원 일원,https://tong.visitkorea.or.kr/cms/resource/71/...,경상북도 경주시 황남동 31-1,경주 대릉원은 경주시 노동동과 황남동에 있는 신라 시대의 고분군을 말하며 노동동 고...,경주문화관광 http://www.gyeongju.go.kr/tour국가유산청 htt...,129.212800,35.838200,1492402,12
4,3336522,통일전 은행나무길,https://tong.visitkorea.or.kr/cms/resource/21/...,경상북도 경주시 칠불암길 6 (남산동),통일전 은행나무길은 경주시의 대표적인 가을 명소로 손꼽히는 곳이라고 할 수 있다. ...,경주문화관광 https://www.gyeongju.go.kr/tour,129.242273,35.798198,3336522,12

In [34]:
df2.nunique()

spot_id            662
name               660
img                507
address            611
overview           658
homepage           354
map_x              651
map_y              650
content_id         662
content_type_id      8
dtype: int64

In [35]:
df2 = df2.drop(columns=['spot_id', 'homepage', 'content_id'])

In [36]:
# 값 분포 카운트
df2['content_type_id'].value_counts()

# 정렬된 형태로
df2['content_type_id'].value_counts().sort_index()

# 비율 포함
df2['content_type_id'].value_counts(dropna=False)

# 비율(%)로 보기
df2['content_type_id'].value_counts(normalize=True) * 100

# 카운트와 비율 함께 보기
pd.DataFrame({
    'count': df2['content_type_id'].value_counts(),
    'percentage': df2['content_type_id'].value_counts(normalize=True) * 100
})

                 count  percentage
content_type_id
39                 212   32.024169
12                 202   30.513595
32                 109   16.465257
28                  53    8.006042
14                  32    4.833837
38                  31    4.682779
25                  16    2.416918
15                   7    1.057402

In [37]:
# content_type_id가 32인 행 드랍
df2 = df2[df2['content_type_id'] != 32]

# 결과 확인
print(f"남은 행 수: {len(df2)}")
print(df2['content_type_id'].value_counts().sort_index())

남은 행 수: 553
content_type_id
12    202
14     32
15      7
25     16
28     53
38     31
39    212
Name: count, dtype: int64

In [38]:
# content_type_id가 25인 행만 출력
print(f"content_type_id가 25인 행: {len(df2[df2['content_type_id'] == 25])}개")
df2[df2['content_type_id'] == 25]

content_type_id가 25인 행: 16개

,name,img,address,overview,map_x,map_y,content_type_id
164,눈으로 보고 마음으로 느끼는 경주 미술·박물관 여행,http://tong.visitkorea.or.kr/cms/resource/67/1...,NaN,경주에서 함께하는 문화여행 신라의 역사와 과학 기술을 알아볼 수 있는 신라역사과학관...,129.193623,35.812524,25
165,불국토 남산에 올라 경주를 굽어보다,http://tong.visitkorea.or.kr/cms/resource/61/1...,NaN,경주 남산은 국립공원으로 지정되어 있을 뿐 아니라 “남산에 오르지 않고 경주를 논하...,129.207505,35.823064,25
173,빛으로 빛나는 경주의 야간투어 코스,http://tong.visitkorea.or.kr/cms/resource/19/1...,NaN,수학여행하면 먼저 떠오르는 경주는 신라의 문화와 역사가 잠들어있는 고고한 도시다. ...,129.286725,35.842642,25
174,"신라의 달밤을 걷는 길, 경주의 백미",http://tong.visitkorea.or.kr/cms/resource/58/7...,NaN,낮보다 아름다운 경주의 밤. 번잡한 길에서 벗어나 신라의 달밤을 걸으며 다양한 문화...,129.222691,35.867426,25
175,회재 이언적 선생의 자취를 찾아서,http://tong.visitkorea.or.kr/cms/resource/90/1...,NaN,안동 하회마을과 함께 세계문화유산에 등재된 경주 양동마을은 오랜 역사와 전통을 간직...,129.254923,35.999882,25
523,"해파랑길(경주, 포항, 영덕 구간)",http://tong.visitkorea.or.kr/cms/resource/56/1...,NaN,해파랑길은 부산 오륙도에서 시작되는 총 750km 대한민국에서 가장 긴 걷기 여행길...,0.000000,0.000000,25
540,천년 전 신라인들을 만나다,http://tong.visitkorea.or.kr/cms/resource/49/2...,NaN,경주는 신라시대와 현대가 공존하는 공간이다. 경주 시내 곳곳에 봉긋 솟아 있는 수많...,129.220251,35.830556,25
601,신라의 불국토 남산에서 부처를 만나다,http://tong.visitkorea.or.kr/cms/resource/14/1...,NaN,"경주 동남산 자락에는 탑곡, 미륵곡, 불곡 등 골짜기마다 신라의 부처님들이 새겨져 ...",129.230800,35.818974,25
618,도보로 즐기는 신라의 여름밤,http://tong.visitkorea.or.kr/cms/resource/58/1...,NaN,경주 야경의 백미는 유네스코가 경주역사유적지구로 지정한 곳 중 하나인 월성 지구다....,129.219092,35.834694,25
627,경주 최고의 문화유산을 만나다,http://tong.visitkorea.or.kr/cms/resource/30/1...,NaN,경주 토함산 자락의 불국사와 석굴암이 우리나라를 대표하는 문화유산 중 하나라는 사실...,129.333045,35.789396,25
656,바다의 용으로 다시 태어난 문무대왕을 찾아서,http://tong.visitkorea.or.kr/cms/resource/35/2...,NaN,"경주 시내에서 토함산을 넘어가면 기림사, 골굴사 등 사찰과 함께 삼국통일의 주역인 ...",129.405577,35.803034,25
657,왕에게 가다,http://tong.visitkorea.or.kr/cms/resource/66/1...,NaN,국립경주박물관으로 들어서면 커다란 종이 보인다. 경덕왕이 아버지를 기리기 위해 만든...,129.187842,35.825069,25
658,버스로 떠나는 제2의 수학여행 양동마을 코스,http://tong.visitkorea.or.kr/cms/resource/34/2...,NaN,도시 전체가 하나의 거대한 신라박물관인 경주. 유네스코 지정 세계문화유산도 52개나...,129.254651,35.999893,25
659,경주의 보물을 만나는 길,http://tong.visitkorea.or.kr/cms/resource/43/1...,NaN,신라문화의 보물 같은 결정체를 보는 여행이다. 경주 여행에 빼 놓을 수 없는 포석정...,129.212863,35.807311,25
660,신라의 화려한 역사와 문화를 만나다,http://tong.visitkorea.or.kr/cms/resource/48/1...,NaN,경주는 신라시대 역사의 산 교육장이다. 답사 여행은 에밀레종으로 잘 알려진 성덕대왕...,129.228603,35.829339,25
661,통일신라의 주역이 잠들어 있는 곳,http://tong.visitkorea.or.kr/cms/resource/61/1...,NaN,경주를 가로지르는 형산강 서쪽은 시내에 비해 사람들의 발길이 뜸하다. 하지만 태종무...,129.192394,35.845334,25

# 전처리

`df1`은 숙소 정보이므로 이번 MVP에서는 사용하지 않고, 관광지/음식점 데이터인 `df2`만 사용합니다. `spot_id`, `content_id`는 추후 API와 연결할 수 있어 유지합니다.

In [39]:
import numpy as np
import pandas as pd
from pathlib import Path

TOUR_SPOT_FILENAME = "_TourSpot__202607062337.csv"
PATH_CANDIDATES = [
    Path(TOUR_SPOT_FILENAME),
    Path("modeling") / TOUR_SPOT_FILENAME,
    Path("../modeling") / TOUR_SPOT_FILENAME,
]

TOUR_SPOT_PATH = next((p for p in PATH_CANDIDATES if p.exists()), None)
if TOUR_SPOT_PATH is None:
    raise FileNotFoundError(f"{TOUR_SPOT_FILENAME} ??? ?? ? ????. ?? ?? ??: {Path.cwd()}")

DATA_DIR = TOUR_SPOT_PATH.parent
spots_raw = pd.read_csv(TOUR_SPOT_PATH)
spots_raw.head()

,spot_id,name,img,content,address,can_parking,can_pet,crowd_level,overview,homepage,map_x,map_y,content_id,content_type_id,tel
0,2910116,라라캠핑장,http://tong.visitkorea.or.kr/cms/resource/96/2...,NaN,경상북도 경주시 서왕길 381-14,NaN,NaN,NaN,라라캠핑장은 경북 경주시 양남면 신대리에 자리 잡았다. 경주시청을 기점으로 40㎞가...,"<a href=""https://cafe.naver.com/lalacamp""targe...",129.396364,35.687767,2910116,28,NaN
1,2904463,장터밥상,https://tong.visitkorea.or.kr/cms/resource/59/...,NaN,경상북도 경주시 동해안로 1998,NaN,NaN,NaN,장터밥상은 경상북도 경주시 감포읍 전촌리에 위치하고 있다. 깔끔한 외관과 고급스러운...,NaN,129.490808,35.785516,2904463,39,NaN
2,127693,골굴사(경주),https://tong.visitkorea.or.kr/cms/resource/89/...,NaN,경상북도 경주시 문무대왕면 기림로 101-5,NaN,NaN,NaN,골굴사는 경주시의 함월산에 위치한 사찰로 선무도(禪武道)의 총본산으로 한국의 소림사...,http://www.golgulsa.com,129.406572,35.802359,127693,12,NaN
3,1492402,경주 대릉원 일원,https://tong.visitkorea.or.kr/cms/resource/71/...,NaN,경상북도 경주시 황남동 31-1,NaN,NaN,NaN,경주 대릉원은 경주시 노동동과 황남동에 있는 신라 시대의 고분군을 말하며 노동동 고...,경주문화관광 http://www.gyeongju.go.kr/tour국가유산청 htt...,129.212800,35.838200,1492402,12,NaN
4,3336522,통일전 은행나무길,https://tong.visitkorea.or.kr/cms/resource/21/...,NaN,경상북도 경주시 칠불암길 6 (남산동),NaN,NaN,NaN,통일전 은행나무길은 경주시의 대표적인 가을 명소로 손꼽히는 곳이라고 할 수 있다. ...,경주문화관광 https://www.gyeongju.go.kr/tour,129.242273,35.798198,3336522,12,NaN

In [40]:
TYPE_NAME = {
    12: "관광지",
    14: "문화시설",
    15: "축제공연행사",
    25: "여행코스",
    28: "레포츠",
    32: "숙박",
    38: "쇼핑",
    39: "음식점",
}

VISIT_TYPE_IDS = [12, 14, 15, 28, 38]
RESTAURANT_TYPE_ID = 39
EXCLUDED_TYPE_IDS = [25, 32]

spots = spots_raw.copy()
spots["type_name"] = spots["content_type_id"].map(TYPE_NAME).fillna("??")

spots = spots[
    spots["map_x"].notna()
    & spots["map_y"].notna()
    & (spots["map_x"] != 0)
    & (spots["map_y"] != 0)
].copy()

spots["overview"] = spots["overview"].fillna("").astype(str)
spots["name"] = spots["name"].fillna("").astype(str)
spots["address"] = spots["address"].fillna("").astype(str)
spots["img"] = spots["img"].fillna("").astype(str)

# ??(32)? ?? ??? ????(25)? ?? ?? ???? ?????.
spots = spots[~spots["content_type_id"].isin(EXCLUDED_TYPE_IDS)].copy()

# overview ???? ????? ???? ??? ??? ?????.
spots["embedding_text"] = (
    "장소명: " + spots["name"] + "\n"
    + "분류: " + spots["type_name"] + "\n"
    + "설명: " + spots["overview"]
)

spots[["spot_id", "content_id", "name", "type_name", "address", "map_x", "map_y", "overview"]].head()

,spot_id,content_id,name,type_name,address,map_x,map_y,overview
0,2910116,2910116,라라캠핑장,레포츠,경상북도 경주시 서왕길 381-14,129.396364,35.687767,라라캠핑장은 경북 경주시 양남면 신대리에 자리 잡았다. 경주시청을 기점으로 40㎞가...
1,2904463,2904463,장터밥상,음식점,경상북도 경주시 동해안로 1998,129.490808,35.785516,장터밥상은 경상북도 경주시 감포읍 전촌리에 위치하고 있다. 깔끔한 외관과 고급스러운...
2,127693,127693,골굴사(경주),관광지,경상북도 경주시 문무대왕면 기림로 101-5,129.406572,35.802359,골굴사는 경주시의 함월산에 위치한 사찰로 선무도(禪武道)의 총본산으로 한국의 소림사...
3,1492402,1492402,경주 대릉원 일원,관광지,경상북도 경주시 황남동 31-1,129.212800,35.838200,경주 대릉원은 경주시 노동동과 황남동에 있는 신라 시대의 고분군을 말하며 노동동 고...
4,3336522,3336522,통일전 은행나무길,관광지,경상북도 경주시 칠불암길 6 (남산동),129.242273,35.798198,통일전 은행나무길은 경주시의 대표적인 가을 명소로 손꼽히는 곳이라고 할 수 있다. ...

In [41]:
print("recommendation rows:", len(spots))
print(spots["type_name"].value_counts())

recommendation rows: 537
type_name
음식점       212
관광지       202
레포츠        53
문화시설       32
쇼핑         31
축제공연행사      7
Name: count, dtype: int64

# 임베딩

한국어 우선 MVP로 `jhgan/ko-sroberta-multitask`를 먼저 사용합니다. 모델을 사용할 수 없는 환경에서는 TF-IDF로 자동 대체하여 테스트를 진행합니다.

In [42]:
import os
import pickle
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer

EMBEDDING_MODEL_NAME = "jhgan/ko-sroberta-multitask"
EMBEDDING_CACHE_PATH = DATA_DIR / "spot_embeddings_ko.pkl"

embedding_backend = None
embedding_model = None
spot_vectors = None
vectorizer = None

try:
    from sentence_transformers import SentenceTransformer

    embedding_backend = "sentence-transformers"
    embedding_model = SentenceTransformer(EMBEDDING_MODEL_NAME)

    if EMBEDDING_CACHE_PATH.exists():
        with open(EMBEDDING_CACHE_PATH, "rb") as f:
            cache = pickle.load(f)
        if cache.get("model_name") == EMBEDDING_MODEL_NAME and cache.get("spot_ids") == spots["spot_id"].tolist():
            spot_vectors = cache["vectors"]

    if spot_vectors is None:
        spot_vectors = embedding_model.encode(
            spots["embedding_text"].tolist(),
            normalize_embeddings=True,
            show_progress_bar=True,
        )
        with open(EMBEDDING_CACHE_PATH, "wb") as f:
            pickle.dump(
                {
                    "model_name": EMBEDDING_MODEL_NAME,
                    "spot_ids": spots["spot_id"].tolist(),
                    "vectors": spot_vectors,
                },
                f,
            )
except Exception as e:
    embedding_backend = "tfidf-fallback"
    print("SentenceTransformer is not available. Using TF-IDF fallback.")
    print("reason:", repr(e))
    vectorizer = TfidfVectorizer(max_features=5000, ngram_range=(1, 2))
    spot_vectors = vectorizer.fit_transform(spots["embedding_text"].tolist())

print("embedding backend:", embedding_backend)
print("vector shape:", getattr(spot_vectors, "shape", None))

SentenceTransformer is not available. Using TF-IDF fallback.
reason: OSError(22, 'DLL 초기화 루틴을 실행할 수 없습니다.', None, 1114)
embedding backend: tfidf-fallback
vector shape: (537, 5000)

In [43]:
def embed_query(text):
    """??? ?? ??? ?? ??? ?? ??? ??? ?????."""
    if embedding_backend == "sentence-transformers":
        return embedding_model.encode([text], normalize_embeddings=True)
    return vectorizer.transform([text])


def get_similarity_scores(query_text):
    query_vector = embed_query(query_text)
    return cosine_similarity(query_vector, spot_vectors)[0]

# 추천 알고리즘

테마와 분위기는 임베딩 유사도로 고르고, 시간/이동수단/음식점 개수는 명확한 규칙으로 처리합니다. 현재 데이터에는 영업시간, 반려동물, 주차, 혼잡도 정보가 없으므로 이번 MVP에서는 사용하지 않습니다.

In [44]:
from math import radians, sin, cos, sqrt, atan2
from datetime import datetime, timedelta

DURATION_CONFIG = {
    "2시간": {"minutes": 120, "restaurant_count": 0, "start_time": "10:00"},
    "반나절": {"minutes": 240, "restaurant_count": 1, "start_time": "10:00"},
    "하루": {"minutes": 480, "restaurant_count": 2, "start_time": "10:00"},
    "1박2일": {"minutes": 960, "restaurant_count": 4, "start_time": "10:00"},
}

TRANSPORT_CONFIG = {
    "도보": {"speed_kmh": 4, "extra_min": 0, "max_leg_km": 3.0},
    "자전거": {"speed_kmh": 12, "extra_min": 0, "max_leg_km": 8.0},
    "대중교통": {"speed_kmh": 18, "extra_min": 10, "max_leg_km": 20.0},
    "자차": {"speed_kmh": 35, "extra_min": 5, "max_leg_km": 50.0},
}

VISIT_MINUTES = {12: 60, 14: 60, 15: 90, 28: 90, 38: 45, 39: 60}

THEME_HINTS = {
    "역사": "신라 역사 문화유산 유적 사찰 왕릉 설화 전통",
    "야경": "야경 밤 조명 노을 월지 월정교 산책",
    "힐링": "자연 숲 휴식 조용한 산책 웰니스",
    "경치": "풍경 전망 바다 산 호수 사진 명소",
    "로컬": "황리단길 골목 시장 카페 지역 분위기 체험",
    "맛집": "음식 맛집 식당 카페 디저트 로컬 먹거리",
    "산책": "걷기 산책 길 거리 공원 둘레길",
    "문화": "문화 예술 박물관 전시 공연 체험",
}

COMPANION_HINTS = {
    "혼자": "혼자 천천히 둘러보기 좋은 조용한 여행",
    "연인": "연인과 데이트하기 좋은 분위기 좋은 여행",
    "가족": "가족과 함께 편하게 방문하기 좋은 여행",
    "친구": "친구와 함께 즐겁게 둘러보기 좋은 여행",
    "동료": "동료와 함께 부담 없이 방문하기 좋은 여행",
}


def haversine_km(lat1, lon1, lat2, lon2):
    R = 6371.0
    dlat = radians(lat2 - lat1)
    dlon = radians(lon2 - lon1)
    a = sin(dlat / 2) ** 2 + cos(radians(lat1)) * cos(radians(lat2)) * sin(dlon / 2) ** 2
    return 2 * R * atan2(sqrt(a), sqrt(1 - a))


def travel_minutes(distance_km, transport):
    cfg = TRANSPORT_CONFIG[transport]
    return int(round((distance_km / cfg["speed_kmh"]) * 60 + cfg["extra_min"]))


def build_user_query(duration, companions, themes, transport):
    if isinstance(themes, str):
        themes = [themes]
    theme_text = ", ".join(themes)
    hint_text = " ".join(THEME_HINTS.get(theme, theme) for theme in themes)
    companion_text = COMPANION_HINTS.get(companions, companions)
    return (
        f"동행 유형은 {companions}이고, {duration} 동안 경주에서 {theme_text} 테마를 즐기는 여행. "
        f"{transport}로 이동 가능한 코스를 선호한다. "
        f"{companion_text}. {hint_text}"
    )


def add_similarity_column(query_text):
    scored = spots.copy()
    scored["similarity"] = get_similarity_scores(query_text)
    scored["visit_minutes"] = scored["content_type_id"].map(VISIT_MINUTES).fillna(60).astype(int)
    return scored

In [45]:
def choose_next_spot(candidates, current_lat, current_lon, transport, used_ids):
    available = candidates[~candidates["spot_id"].isin(used_ids)].copy()
    if available.empty:
        return None

    available["distance_from_prev_km"] = available.apply(
        lambda row: haversine_km(current_lat, current_lon, row["map_y"], row["map_x"]),
        axis=1,
    )

    max_leg = TRANSPORT_CONFIG[transport]["max_leg_km"]
    near = available[available["distance_from_prev_km"] <= max_leg].copy()
    if near.empty:
        near = available.copy()

    near["route_score"] = near["similarity"] - (near["distance_from_prev_km"] * 0.015)
    return near.sort_values(["route_score", "similarity"], ascending=False).iloc[0]


def pick_restaurant(restaurants, current_lat, current_lon, transport, used_ids):
    available = restaurants[~restaurants["spot_id"].isin(used_ids)].copy()
    if available.empty:
        return None

    available["distance_from_prev_km"] = available.apply(
        lambda row: haversine_km(current_lat, current_lon, row["map_y"], row["map_x"]),
        axis=1,
    )
    max_leg = TRANSPORT_CONFIG[transport]["max_leg_km"]
    near = available[available["distance_from_prev_km"] <= max_leg].copy()
    if near.empty:
        near = available.copy()

    near["route_score"] = near["similarity"] - (near["distance_from_prev_km"] * 0.02)
    return near.sort_values(["route_score", "similarity"], ascending=False).iloc[0]


def restaurant_slots(duration, restaurant_count):
    if restaurant_count == 0:
        return []
    if duration == "반나절":
        return [2]
    if duration == "하루":
        return [2, 5]
    if duration == "1박2일":
        return [2, 5, 8, 11]
    return []

In [46]:
def recommend_course(
    duration="하루",
    companions="연인",
    themes=None,
    transport="도보",
    start_lat=None,
    start_lon=None,
    top_n=40,
):
    """?? CSV ???? ??? ??? + ??? ??? ?????."""
    if themes is None:
        themes = ["역사"]
    if isinstance(themes, str):
        themes = [themes]

    if duration not in DURATION_CONFIG:
        raise ValueError(f"duration? {list(DURATION_CONFIG)} ? ???? ???.")
    if transport not in TRANSPORT_CONFIG:
        raise ValueError(f"transport? {list(TRANSPORT_CONFIG)} ? ???? ???.")

    config = DURATION_CONFIG[duration]
    total_budget = config["minutes"]
    restaurant_count = config["restaurant_count"]
    query_text = build_user_query(duration, companions, themes, transport)
    scored = add_similarity_column(query_text)

    visit_candidates = scored[scored["content_type_id"].isin(VISIT_TYPE_IDS)].nlargest(top_n, "similarity").copy()
    restaurant_candidates = scored[scored["content_type_id"] == RESTAURANT_TYPE_ID].nlargest(max(top_n, 30), "similarity").copy()

    if visit_candidates.empty:
        raise ValueError("?? ??? ??? ??? ????.")

    used_ids = set()
    route = []
    elapsed = 0

    if start_lat is None or start_lon is None:
        first = visit_candidates.iloc[0].copy()
        first["distance_from_prev_km"] = 0.0
        first["travel_minutes"] = 0
    else:
        first = choose_next_spot(visit_candidates, start_lat, start_lon, transport, used_ids)
        first["travel_minutes"] = travel_minutes(first["distance_from_prev_km"], transport)

    route.append(first)
    used_ids.add(int(first["spot_id"]))
    elapsed += int(first["travel_minutes"]) + int(first["visit_minutes"])
    current_lat, current_lon = float(first["map_y"]), float(first["map_x"])

    slots = restaurant_slots(duration, restaurant_count)
    inserted_restaurants = 0
    step = 1

    while elapsed < total_budget:
        should_insert_restaurant = inserted_restaurants < restaurant_count and step in slots

        if should_insert_restaurant:
            next_spot = pick_restaurant(restaurant_candidates, current_lat, current_lon, transport, used_ids)
            inserted_restaurants += 1
        else:
            next_spot = choose_next_spot(visit_candidates, current_lat, current_lon, transport, used_ids)

        if next_spot is None:
            break

        next_spot = next_spot.copy()
        if "distance_from_prev_km" not in next_spot or pd.isna(next_spot["distance_from_prev_km"]):
            next_spot["distance_from_prev_km"] = haversine_km(current_lat, current_lon, next_spot["map_y"], next_spot["map_x"])
        next_spot["travel_minutes"] = travel_minutes(float(next_spot["distance_from_prev_km"]), transport)

        added_time = int(next_spot["travel_minutes"]) + int(next_spot["visit_minutes"])
        if elapsed + added_time > total_budget:
            break

        route.append(next_spot)
        used_ids.add(int(next_spot["spot_id"]))
        elapsed += added_time
        current_lat, current_lon = float(next_spot["map_y"]), float(next_spot["map_x"])
        step += 1

    result = pd.DataFrame(route).reset_index(drop=True)
    result["order"] = result.index + 1

    start_dt = datetime.strptime(config["start_time"], "%H:%M")
    current_dt = start_dt
    arrivals, leaves, day_labels = [], [], []

    for _, row in result.iterrows():
        current_dt += timedelta(minutes=int(row["travel_minutes"]))
        arrivals.append(current_dt.strftime("%H:%M"))
        current_dt += timedelta(minutes=int(row["visit_minutes"]))
        leaves.append(current_dt.strftime("%H:%M"))
        day_labels.append(1 if int((current_dt - start_dt).total_seconds() // 60) <= 480 else 2)

    result["day"] = day_labels
    result["arrival_time"] = arrivals
    result["leave_time"] = leaves
    result["distance_from_prev_km"] = result["distance_from_prev_km"].astype(float).round(2)
    result["similarity"] = result["similarity"].astype(float).round(4)
    result["reason"] = result.apply(
        lambda row: f"'{', '.join(themes)}' ??? ??? ???? ??, ?? ???? ? {row['distance_from_prev_km']}km ??? ????.",
        axis=1,
    )

    columns = [
        "day", "order", "name", "type_name", "address", "similarity",
        "distance_from_prev_km", "travel_minutes", "visit_minutes",
        "arrival_time", "leave_time", "reason", "spot_id", "content_id", "content_type_id", "img",
    ]
    result = result[columns]

    summary = {
        "query": query_text,
        "duration": duration,
        "companions": companions,
        "themes": themes,
        "transport": transport,
        "total_places": len(result),
        "restaurant_count": int((result["content_type_id"] == RESTAURANT_TYPE_ID).sum()),
        "target_restaurant_count": restaurant_count,
        "total_distance_km": round(float(result["distance_from_prev_km"].sum()), 2),
        "total_time_minutes": int(result["travel_minutes"].sum() + result["visit_minutes"].sum()),
        "time_budget_minutes": total_budget,
        "embedding_backend": embedding_backend,
    }
    return result, summary

# 테스트

아래 입력값만 바꿔가며 추천 결과를 확인하면 됩니다. 현재 이동시간은 실제 길찾기가 아닌 좌표 기반 추정값입니다.

In [47]:
course, summary = recommend_course(
    duration="반나절",
    companions="연인",
    themes=["역사", "야경"],
    transport="도보",
)

summary

{'query': '동행 유형은 연인이고, 반나절 동안 경주에서 역사, 야경 테마를 즐기는 여행. 도보로 이동 가능한 코스를 선호한다. 연인과 데이트하기 좋은 분위기 좋은 여행. 신라 역사 문화유산 유적 사찰 왕릉 설화 전통 야경 밤 조명 노을 월지 월정교 산책',
 'duration': '반나절',
 'companions': '연인',
 'themes': ['역사', '야경'],
 'transport': '도보',
 'total_places': 3,
 'restaurant_count': 1,
 'target_restaurant_count': 1,
 'total_distance_km': 1.02,
 'total_time_minutes': 196,
 'time_budget_minutes': 240,
 'embedding_backend': 'tfidf-fallback'}

In [48]:
course[[
    "day", "order", "name", "type_name", "similarity",
    "distance_from_prev_km", "travel_minutes", "visit_minutes",
    "arrival_time", "leave_time", "reason"
]]

,day,order,name,type_name,similarity,distance_from_prev_km,travel_minutes,visit_minutes,arrival_time,leave_time,reason
0,1,1,월정교,관광지,0.1402,0.00,0,60,10:00,11:00,"'역사, 야경' ??? ??? ???? ??, ?? ???? ? 0.0km ??? ..."
1,1,2,경주 교촌마을,관광지,0.0836,0.31,5,60,11:05,12:05,"'역사, 야경' ??? ??? ???? ??, ?? ???? ? 0.31km ???..."
2,1,3,델레테테,음식점,0.1184,0.71,11,60,12:16,13:16,"'역사, 야경' ??? ??? ???? ??, ?? ???? ? 0.71km ???..."

In [49]:
course2, summary2 = recommend_course(
    duration="하루",
    companions="가족",
    themes=["경치", "문화"],
    transport="자차",
)

summary2

{'query': '동행 유형은 가족이고, 하루 동안 경주에서 경치, 문화 테마를 즐기는 여행. 자차로 이동 가능한 코스를 선호한다. 가족과 함께 편하게 방문하기 좋은 여행. 풍경 전망 바다 산 호수 사진 명소 문화 예술 박물관 전시 공연 체험',
 'duration': '하루',
 'companions': '가족',
 'themes': ['경치', '문화'],
 'transport': '자차',
 'total_places': 6,
 'restaurant_count': 2,
 'target_restaurant_count': 2,
 'total_distance_km': 4.87,
 'total_time_minutes': 453,
 'time_budget_minutes': 480,
 'embedding_backend': 'tfidf-fallback'}

In [50]:
course2[[
    "day", "order", "name", "type_name", "similarity",
    "distance_from_prev_km", "travel_minutes", "visit_minutes",
    "arrival_time", "leave_time"
]]

,day,order,name,type_name,similarity,distance_from_prev_km,travel_minutes,visit_minutes,arrival_time,leave_time
0,1,1,경주엑스포대공원,관광지,0.3125,0.00,0,60,10:00,11:00
1,1,2,보불ATV체험장,레포츠,0.1430,0.92,7,90,11:07,12:37
2,1,3,보문갈비,음식점,0.0920,1.39,7,60,12:44,13:44
3,1,4,또봇정크아트뮤지엄,문화시설,0.0989,0.83,6,60,13:50,14:50
4,1,5,경주루지월드,레포츠,0.0986,1.61,8,90,14:58,16:28
5,1,6,보문민속식당,음식점,0.0351,0.12,5,60,16:33,17:33